### PR TITLE
Added ability to remove a record when rails authentication is required.

### PR DESCRIPTION
**Pull request by majioa**
Added ability to remove a record when rails authentication is required. In this case scrf-token is added to DELETE request.

### CODE REVIEW

**Comment by antpaw** [comment]
thank you so much for make this a distinct pull request. Can you tell me why mootools_ujs (the rails driver) that is included doesn't do it already https://github.com/kevinvaldek/mootools-ujs/blob/master/Source/rails.js#L62 ?

**Comment by majioa** [comment]
@antpaw I don't know, in my investigations if data remote isn't true , the simple click is occurred (without xhr)

**Comment by antpaw** [comment]
okay, we need data-remote=true attribute on this link, why did you removed it?

**Comment by majioa** [comment]
@antpaw we dont need it, because it forses to do an additional request, well Ill try to reuse the UI code...

**Comment by majioa** [comment]
@antpaw  I validated the UI version, it does a `HTML` request not a JS/JSON, so can't be used as a dynamic destroy method.

**Comment by antpaw** [comment]
okay thanks I understand this now. in the jquery driver https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L113 there is a attribute `data`. I will fix mootools_ujs so it can work with this just like jquery-ujs, and we will only have to put 'json' attribute on this link element.

**Comment by majioa** [comment]
ok

**Comment by antpaw** [comment]
I have just pushed 0.10.13 https://github.com/antpaw/bhf/commit/ed61243b3864fe55d5724e0922dad130c8bc5eb0

**Pull request closed without merging**
