### PR TITLE
Application controller as a concern

### PR DESCRIPTION
**Pull request by majioa**
Application controller was moved into the library module. Now It can be reused in upper level application. Ability to define `devise` as a default auth engine.

### CODE REVIEW

**Comment by antpaw** [comment]
Hey, love your pull request.
Is it possible to remove this lines?
https://github.com/majioa/bhf/blob/master/lib/bhf/controller/extension.rb#L10-L11
https://github.com/majioa/bhf/blob/e3c1c4b10d354c6c95357f0b7a835440ece6f41b/lib/bhf.rb#L50

And do it like this:

````ruby
class Bhf::ApplicationController < ActionController::Base
  include Bhf::Extension::ApplicationController
  protect_from_forgery
  before_filter :authenticate_user! # <<<< business logic of the app

  def check_admin_account
    current_user.is_admin? # Here expression must be evaluated to `true` if user is admin.
  end
end
````

also I'm not sure about `protect_from_forgery`. `csrf_meta_tags` are not set in the html layout. I've skiped this because it's impossible to access the pages anyway from the outside without auth. Maybe we need to remove `protect_from_forgery`?

**Comment by majioa** [comment]
Why do you wish to remove the dynamic devise support? `:authenticate_user` should alway be called when devise authentication is used...

**Comment by antpaw** [comment]
I just wish that bhf will stay completely agnostic to any sort of authentication systems.

**Comment by majioa** [comment]
@antpaw removed

**Comment by antpaw** [comment]
Thank you, I will merge it over the weekend, what are you thoughts on `protect_from_forgery`?

**Comment by antpaw** [comment]
I've just merged most of your commits and created a gem. I didn't merge the #29dccb4 and #2a914de they are too specific and this code can be done inside the main_app. Here is how to add custom html partials to form and table. This [Config](https://github.com/antpaw/bhf-demo-advanced/blob/master/config/bhf/admin.yml#L10) can also have any other type, as long the partial is provided in the main_app view tree. If you wish to build something more abstract and use it accross multiple applications, build a "plugin" like this one https://github.com/antpaw/ksk it's basicly an additional RailsEngine that you can and use it as a holder for all the additional logic that you want to add on top of bhf. https://github.com/antpaw/ksk/blob/master/lib/ksk.rb you can even modify bhf settings and mount own routes https://github.com/antpaw/ksk/blob/master/config/routes.rb with own controllers that extend bhf_controller and reuse bhf_layout or anything else.

Thank you for you pull request

**Comment by antpaw** [comment]
if you have any question, just post them in issues and label them as "question"

**Comment by majioa** [comment]
@antpaw just why dot you merge a type feature, it is standard rails field? also image/file ?

**Comment by antpaw** [comment]
I'm pretty sure "type" is not a sql nor ruby standard var type. I think it's something that carrierwave need internally, if you want to add a carrierwave support, do it more abstract like i did it for paperclip, you cant use 'file' or 'type' namespace in your partial names, ect.

**Pull request closed without merging**
